Repository WolfyzDev/Ressources, pull requests merged in 2022-06, with the labels that each got.

#15 Règles et contributeurs
  README.md
  SECURITY.md
Labels: Validation par View

#26 Ajouter le nouveau Issue Form
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/proposer-une-ressource.md
  .github/ISSUE_TEMPLATE/proposer-une-ressource.yml
Labels: Configuration, Fork

#42 Milestone template
  .github/ISSUE_TEMPLATE/milestones.yml
Labels: Configuration, Validation par View

#45 Repair bug template milestone
  .github/ISSUE_TEMPLATE/milestones.yml
Labels: bug, Configuration

#48 Création de la catégorie Logiciel & Outil
  Logiciels_et_outils/Unlayer.md
  Logiciels_et_outils/sommaire.md
Labels: En construction

#55 Create Cheat-Sheet_VIM.md
  Logiciels_et_outils/Cheat-Sheet_VIM.md
  Logiciels_et_outils/Vim Cheat Sheet fr.pdf
  Logiciels_et_outils/Vim Cheat Sheet_en.pdf
Labels: Validation par View, En construction, Task

#54 Create sommaire_general.md
  sommaire_general.md
Labels: Validation par View

#59 Tentative de correction
  Logiciels_et_outils/Cheat-Sheet_VIM.md
Labels: bug, Validation par View

#60 Modification mineurs
  CONTRIBUTING.md
Labels: Validation par View

#61 Modification sommaire vim
  Logiciels_et_outils/sommaire.md
  sommaire_general.md
Labels: Validation par View

#62 Bug file in vim cheat sheet patch1
  Logiciels_et_outils/Cheat-Sheet_VIM.md
  Logiciels_et_outils/VimCheatSheet_en.pdf
  Logiciels_et_outils/VimCheatSheet_fr.pdf
Labels: Validation par View

#65 patch all
  .github/workflows/greetings.yml
  App_et_langages/sommaire.md
  Architecture_et_cybersecurite/Architecture_et_cybersecurite.md
  Autres/bot_et_serveur/bot_et_serveur.md
  Autres/git_et_github/git_et_github.md
  Autres/sommaire.md
  Backend/sommaire.md
  Challenge_et_jeux/Challenge_et_jeux.md
  Creation_de_site_front_et_design/Creation_de_site_front_et_design.md
  Logiciels_et_outils/Cheat-Sheet_VIM.md
  Logiciels_et_outils/Unlayer.md
  Logiciels_et_outils/sommaire.md
  Python/sommaire.md
  README.md
  index.html
  retype.yml
Labels: Configuration, Alice est passé par là
